name: Publish Library

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  contents: write  # Required to create a release

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

#      - name: Import GPG Key
#        env:
#          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
#          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
#        run: |
#          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
#          echo "allow-preset-passphrase" >> ~/.gnupg/gpg-agent.conf
#          gpg --batch --pinentry-mode loopback --passphrase "$GPG_PASSPHRASE" --export-secret-keys > secret.asc

      - name: Set Version Based on Branch
        run: |
          chmod +x versioning.sh
          ./github/workflows/versioning.sh

#      - name: Publish to Maven Central
#        run: ./gradlew publish
#        env:
#          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
#          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
#          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Publish to JitPack (if required)
        run: echo "JitPack auto-builds from GitHub"

      - name: Create GitHub Release
        if: github.ref == 'refs/heads/feature/.*'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
